sudo: required
dist: trusty

language: haxe
haxe:
- 3.2.1
- development

matrix:
  allow_failures:
  - haxe: development

install:
- haxelib install travix
- haxelib run travix install

script:
- haxelib run travix node

env:
  secure: T4SCtY5qmEsK1ARWPevJmqLm23tv4CobLrbPOQV3FsoQno7FCP1S/+9GmuoJKzeTjWMzdTeDsp8TVwZ6AyGjvhl2nZNjhU+QTsir4tfbYYRyvsz/QK6pveFbPQVv7OsnnaB4wbZtqGZ8mzFeQf7Ol4tsNe7iUFJb/iVc+4/lUxo=

deploy:
  provider: script
  script: haxelib run travix release
  on:
    tags: true
    all_branches: true
